class Publisher_int32:
    def __init__(self, topic_name: str): ...
    def setValue(self, value: int) -> None: ...
    def publish(self, value: int) -> None: ...
    # ... more methods

class Subscriber_int32:
    def __init__(self, topic_name: str, subscriber_name: str, do_subscribe: bool = False): ...
    def readWait(self) -> int: ...
    # ... more methods